import type { Metadata } from "next";
import "../globals.css";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session, user } = await getUser();
  if (session && user.role === "admin") {
    return redirect("/dashboard");
  }
  if (session && user.role === "customer") {
    return redirect("/");
  }

  return <div>{children}</div>;
}
