import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Homepages",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex justify-center items-center">
        <div className="max-w-sm">{children}</div>
      </div>
    </>
  );
}
