import type { Metadata } from "next";
import "../../globals.css";
import Navbar from "./_components/navbar";

export const metadata: Metadata = {
  title: "Homepages",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex justify-center items-center">
      <div className="flex flex-col justify-center items-start w-full max-w-sm">
        <Navbar />
        {children}
      </div>
    </div>
  );
}
